// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ_myto55SBru_2Zcwo5vrri4TO3QLWXo',
    appId: '1:922413793804:web:06e3825c4af60720bde429',
    messagingSenderId: '922413793804',
    projectId: 'grocerypicker-862b3',
    authDomain: 'grocerypicker-862b3.firebaseapp.com',
    databaseURL: 'https://grocerypicker-862b3-default-rtdb.firebaseio.com',
    storageBucket: 'grocerypicker-862b3.appspot.com',
    measurementId: 'G-LXMQQV4W79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeXRY1p3tycE-6gh1gbRfSbG-0GMXfFzE',
    appId: '1:922413793804:android:0e0fbbdcac3b2fa1bde429',
    messagingSenderId: '922413793804',
    projectId: 'grocerypicker-862b3',
    databaseURL: 'https://grocerypicker-862b3-default-rtdb.firebaseio.com',
    storageBucket: 'grocerypicker-862b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLwk8IyG80MfGZfcM3wdgvjU2KyyHMm_g',
    appId: '1:922413793804:ios:fe2193e99163385fbde429',
    messagingSenderId: '922413793804',
    projectId: 'grocerypicker-862b3',
    databaseURL: 'https://grocerypicker-862b3-default-rtdb.firebaseio.com',
    storageBucket: 'grocerypicker-862b3.appspot.com',
    iosClientId: '922413793804-gc02g2pemn3rl6ff55mroacqrl1vdog6.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryPicker',
  );
}
